--
-- PostgreSQL database dump
--

\restrict qxxbNknmdwsqN7qyc2cSHvCW4RhWNtmJnB0djpqYcZehmVdxStk3eyRrzekpwrn

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bill (
    id integer NOT NULL,
    clientid integer,
    productname character varying(255),
    quantity integer,
    createdat timestamp without time zone
);


ALTER TABLE public.bill OWNER TO postgres;

--
-- Name: bill_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    address character varying(255) NOT NULL,
    email character varying(100) NOT NULL,
    age integer NOT NULL
);


ALTER TABLE public.client OWNER TO postgres;

--
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    clientid integer,
    productid integer,
    quantity integer NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bill; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.bill VALUES (1, 1, 'Monitor LED', 5, '2026-05-13 20:08:10.560401');
INSERT INTO public.bill VALUES (2, 1, 'Monitor LED', 3, '2026-05-13 20:09:06.873067');
INSERT INTO public.bill VALUES (3, 1, 'Monitor LED', 3, '2026-05-13 20:09:14.859741');
INSERT INTO public.bill VALUES (4, 2, 'Monitor LED', 5, '2026-05-13 20:15:34.559584');
INSERT INTO public.bill VALUES (5, 3, 'laptop gaming', 10, '2026-05-13 20:18:49.845237');
INSERT INTO public.bill VALUES (6, 1, 'Monitor LED', 7, '2026-05-13 20:29:54.102844');
INSERT INTO public.bill VALUES (7, 6, 'laptop gaming', 7, '2026-05-14 17:43:44.274282');
INSERT INTO public.bill VALUES (8, 1, 'laptop gaming', 2, '2026-05-14 17:47:54.548288');
INSERT INTO public.bill VALUES (9, 6, 'iphone 15', 1, '2026-05-14 17:48:06.813267');


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.client VALUES (1, 'Andrei Test', 'Str. Clujului 10', 'andrei@email.com', 25);
INSERT INTO public.client VALUES (6, 'mfs', 'Str Bucuresti', 'f@s', 25);


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.orders VALUES (1, 1, 1, 5);
INSERT INTO public.orders VALUES (2, 1, 1, 3);
INSERT INTO public.orders VALUES (3, 1, 1, 3);
INSERT INTO public.orders VALUES (4, 2, 2, 5);
INSERT INTO public.orders VALUES (5, 3, 3, 10);
INSERT INTO public.orders VALUES (6, 1, 1, 7);
INSERT INTO public.orders VALUES (7, 6, 3, 7);
INSERT INTO public.orders VALUES (8, 1, 3, 2);
INSERT INTO public.orders VALUES (9, 6, 4, 1);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product VALUES (3, 'laptop gaming', 15);
INSERT INTO public.product VALUES (4, 'iphone 15', 11);


--
-- Name: bill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bill_id_seq', 1, false);


--
-- Name: client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_id_seq', 6, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 9, true);


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 4, true);


--
-- Name: bill bill_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bill
    ADD CONSTRAINT bill_pk PRIMARY KEY (id);


--
-- Name: client client_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pk PRIMARY KEY (id);


--
-- Name: orders orders_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pk PRIMARY KEY (id);


--
-- Name: product product_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pk PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict qxxbNknmdwsqN7qyc2cSHvCW4RhWNtmJnB0djpqYcZehmVdxStk3eyRrzekpwrn

